# Generated by Django 5.0 on 2024-03-16 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_task_repeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 16, 17, 50, 28, 81762)),
        ),
    ]
