# Generated by Django 5.0 on 2024-04-10 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_reminder_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 10, 14, 12, 56, 665562)),
        ),
    ]
