# Generated by Django 5.0 on 2024-07-28 04:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_task_assign_alter_participation_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 28, 8, 14, 30, 748207)),
        ),
    ]
